theme: minima
linkedin_badge: |
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="reiddhughes" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://www.linkedin.com/in/reiddhughes?trk=profile-badge">Reid Hughes</a></div>